### ISSUE TITLE
Teamcity rebuilds PRs if someone comments on it after long time

### ISSUE THREAD

**Issue by Kubuxu** [ipfs/infrastructure#170]
Teamcity seems to forget PR status and starts rebuild if there is any activity on the PR, even comments.

Sorry if it wrong repo.

**Comment by whyrusleeping** [comment]
The actual issue here is that when there is new activity on older PRs, github will create a new merge commit behind the scenes merging the code with the latest master. Teamcity picks up on this and says "hey, i don't know if this code still works when merged into master, lets check to make sure" and reruns the tests

**Comment by lgierth** [comment]
I think this might actually be useful

**Comment by Kubuxu** [comment]
It might be useful, but sometimes it results in queues on tenths if not more PRs.

**Comment by lgierth** [comment]
Closing as we've moved to Jenkins
