### ISSUE TITLE
The Gateways are down

### ISSUE THREAD

**Issue by daviddias** [ipfs/infrastructure#435]
<img width="1009" alt="image" src="https://user-images.githubusercontent.com/1211152/46241478-36c94800-c3c3-11e8-8902-32217ea759c2.png">

<img width="878" alt="image" src="https://user-images.githubusercontent.com/1211152/46241480-39c43880-c3c3-11e8-988b-1eb61376313a.png">

**Comment by eefahy** [comment]
Things have gotten back to normal on the LBs but the wantlist on gateway node got out of hand. Turns out that the disk space underneath IPFS had run out, causing the daemon to wedge itself. I needed to manually delete some blocks in order to get the daemon to startup again, ran gc, and now everything's back to normal.
