### ISSUE TITLE
Out of date certificate for node0.preload.ipfs.io

### ISSUE THREAD

**Issue by Stebalien** [ipfs/infrastructure#443]
Reported here: https://discuss.ipfs.io/t/certs-are-out-of-date/4131

**Comment by kyledrake** [comment]
This was a legacy setup on an older machine and the certificate expired. I've patched it with a new cert for now.

I'm going to move this to its own infrastructure, where the cert will auto-update, preventing this in the future.

I think we need to bear in mind that this is a distributed system failing because of a centralized hack. Whenever we see things like this, it's important to make sure that we're making progress to get rid of them and not forgetting that they're there. @lidel @alanshaw

**Comment by kyledrake** [comment]
This particular issue has been resolved, so I will close this.
