### ISSUE TITLE
Storagebot

### ISSUE THREAD

**Issue by lgierth** [ipfs/infrastructure#63]
An IRC bot similar to pinbot, but pins only on the storage hosts.

**Comment by jbenet** [comment]
maybe we should just move "pinbot" to the two storage hosts. because pinbot storage will get very big. the `seeding/refs-to-seed` thing is pretty large alraedy. that way the gateways can use all their storage to cache hot things?

(maybe excepted: the ipfs.io website? what other things do we need on the gateway fast?)

**Comment by S1L3NTone** [comment]
now i get it slightly?

**Comment by lgierth** [comment]
This is gonna be take care off by moving to pinbot to ipfs-cluster
