### ISSUE TITLE
Matrix server

### ISSUE THREAD

**Issue by davidar** [ipfs/infrastructure#86]
It would be good for ipfs.io to run a [Matrix homeserver](https://github.com/matrix-org/synapse) and an official [IRC bridge](https://github.com/matrix-org/matrix-appservice-irc) for #ipfs, if only so that the webchat doesn't go offline if something happens to matrix.org. I haven't personally set these up before, but I'm told it's reasonably easy to do. Opening an issue to discuss the best way to go about this.

Cc: @jbenet @lgierth @ara4n davidar/vector-web#2

**Comment by ara4n** [comment]
The problem on running an IRC bridge for a largeish community like freenode's #ipfs is that the bridge needs to maintain a separate client connection to the IRC network for each matrix user.  To avoid hitting the per-IP limits on the network you either need a dedicated connection class config (I:line), which is what we've done for the matrix.org connection to Freenode, or mess around allocating a separate IPv6 source IP to every client connection (like IRCCloud does).  If your infrastructure has IPv6 support, the latter is probably the easiest route.  Otherwise you may be better off using the matrix.org bridge rather than Freenode being flooded with requests for additional connection classes.  IIRC you get 30 connections per IP currently on freenode.

**Comment by lgierth** [comment]
We only get 8 IPv6 addresses from DigitalOcean per droplet, but we're obviously not tied to them.

**Comment by davidar** [comment]
@lgierth wow, even my cheap vps gets a /64

**Comment by lgierth** [comment]
Closing this for now, it's out of scope for me personally
